name: Package Permissions
on:
    schedule:
        - cron: "0 0 * * *" # Runs daily
    workflow_dispatch: # Allow manual trigger

jobs:
    sync-permissions:
        runs-on: ubuntu-latest
        steps:
            - name: Sync package permissions with org
              uses: actions/github-script@v6
              with:
                  github-token: ${{ secrets.ADMIN_TOKEN }}
                  script: |
                      const org = 'noise-xyz';  // Your org name
                      const package = 'noise-types';  // Your package name

                      // Get all org members
                      const members = await github.paginate(
                        github.rest.orgs.listMembers,
                        { org }
                      );

                      // Update package permissions
                      for (const member of members) {
                        try {
                          await github.rest.packages.addPackagePermissionsToUser({
                            packageType: 'npm',
                            org,
                            package_name: package,
                            username: member.login,
                            permissions: 'read'
                          });
                        } catch (error) {
                          console.log(`Error setting permissions for ${member.login}: ${error}`);
                        }
                      }
